meta_product_name: "allSmart"
meta_title: "allSmart - Play.Learn.Discover!"
meta_description: "tba"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards