meta_product_name: "allSmart"
meta_title: "allSmart - Play.Learn.Discover!"
meta_description: "Learning made fun with educational games for first-grade children"
meta_image: "https://res.cloudinary.com/djznzpxie/image/upload/v1604930354/Screenshot_2020-11-09_at_13.59.03_ltx6s5.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
